version: '3.8'
services:
  vpn-panel:
    build: .
    ports:
      - "2053:2053"
      - "443:443"
    volumes:
      - ./data:/etc/x-ui
      - ./cert:/root/cert
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    restart: unless-stopped
    network_mode: host

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  fail2ban:
    image: crazymax/fail2ban:latest
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./fail2ban:/data
      - /var/log:/var/log:ro

volumes:
  redis-data:
